using System;

namespace IsValidDnaSequence1
{
    [TestFixture]
    public class IsValidDnaSequence
    {
     

        [Test]
        public bool Verification()
        {
            //arrange
            string DNA = "TCTAATAGCACACACCGGGCAATACGAGCTCAAGCCAGTCTCGCAGTAACGCTCATCAGCAAACGAAAGAGTTTAAGGCTCGCTAATTCGCACTGTCAGGGTCCCTTGGGTGTTTTGCACTAGCGTCAGGTAGGCTAGTATGTGTTTTTCCTTCCAGGGGTATGTGGCTGCGTGGTCAAATGTGCGGCATACGTATTTGCTCGGCGTGCTTGCTCTCACGAACTTGACCTGGAGATCAAGGAGATGTTTCTTGTCCAACTGGACAGCGCTTCAACGGAATGGATCTACGTTACAGCCTGCATAAAGAAAACGGAGTTGCCGAGGACGAAAGCGACTTTAGGTTCTGTCCGTTGTCTTTGGCGGAAAACTTCCACTCAGGAAGCAGACACTGATTGACACGGTTTAGCAGAAGGTTTGAGGATTAGGTCAAATTGAGTGGTTTAATATCGGTATGTCTGGGATTAAAGTATAGTATAGTGCGCTAATCGGAGACGAATTTAAGACACGAGTTCCCAAAACCAAGCGGGCTCACTACGACGGTTAATCCTGGTAGTTTACGTGAACAATGTCCTGAAGAAAATTTATGAAAGAAGGACCCCTCATCGCCTAGAATTACCTACAACGGTCGACCATACCTTCGATTGTCGTGGCCACCCTCGGATTACACGGCAGAGGTGGTTGTGTTGCGATAGGCCAGTATATTATTCTAAGGCGTTACCCCAATGGATTTCCGTCGGAATTGCTATAGCCCTTGAACGCTACATGCACGATACCAAGTTATGTATGGACCGGGTCATCAATAGGTTATAGCCTTGTAGTTAACATGTAGCCCGGCCCTATTAGTACAGTAGTGCCTTCATCGGCATTCTGTTTATTAAGTTTTTTCTACAGCAAAACGATCAAGTGCACTTCCACAGAGCGCGGTAGAGACTCATCCACCCGGCAGCTCTGTAATAGGGACTAAAAAAGTGATGATAATCATGAGTGCCGCGTTATGGTG";

            //act
            bool result = Program.VerificationDNA(DNA);
            //assert
            if (result == true) Console.WriteLine("DNA is ok <3");
            else Console.WriteLine("DNA is not ok :( ");

            return true;
        }
    }
}
